version: '3.8'

services:
  cafedebugdb:
    container_name: cafedebugdb
    image: mysql:8.0
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: cafedebug-mysql-local
    ports:
      - "3307:3306"
  
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - ./svc/minio/data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 8

  minio-mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command:
      - >
        until mc --insecure alias set myminio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do echo waiting for minio; sleep 2; done;
        mc --insecure mb --ignore-existing myminio/cafedebug-uploads;
        mc --insecure mb --ignore-existing myminio/cafedebug-images;
        mc --insecure mb --ignore-existing myminio/cafedebug-bucket;
        mc --insecure mb --ignore-existing myminio/breakingbad-bucket;
        mc --insecure anonymous set download myminio/cafedebug-uploads;
        mc --insecure anonymous set download myminio/cafedebug-images;
        mc --insecure anonymous set download myminio/cafedebug-bucket;
        mc --insecure anonymous set download myminio/breakingbad-bucket;
        echo "Minio buckets ensured."
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
